language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

services:
  - docker

script:
  - go build && go test -v -race ./...
  - docker build -t sinnott74/todoservice:0.0.1 .

after_script:
  - docker images

before_deploy:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
  - docker push sinnott74/todoservice:0.0.1

  # Deploy
  # Bluemix
deploy:
  - provider: cloudfoundry
    username: ${IBM_CLOUD_USER}
    #########################
    ## Add BLUEMIX_PASSWORD environment variable to your Travis project's settings
    ## https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
    #########################
    password: ${IBM_CLOUD_PASSWORD}
    organization: ${IBM_CLOUD_USER}
    space: production
    region: eu-gb
    api: https://api.eu-gb.bluemix.net
    skip_cleanup: true
    on:
      branch: master
  - provider: cloudfoundry
    username: ${IBM_CLOUD_USER}
    #########################
    ## Add BLUEMIX_PASSWORD environment variable to your Travis project's settings
    ## https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
    #########################
    password: ${IBM_CLOUD_PASSWORD}
    organization: ${IBM_CLOUD_USER}
    space: staging
    region: eu-gb
    api: https://api.eu-gb.bluemix.net
    skip_cleanup: true
    on:
      branch: staging
